---
title: "Assignment 4 Task 2"
author: "Logan Babcock"
date: "November 4, 2021"
output: html_document
---

```{r setup, include=FALSE, messages = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = FALSE,  messages = FALSE, warning = FALSE)

library(tidyverse)
library(here)
library(janitor)
library(kableExtra)

hares_raw <- read.csv(here("data", "bonanza_hares.csv"))

```

## 1. Overview
This is an exploratory report on juvenile snoeshoe hares (*Lepus americanus*) using data collected during the  US Long Term Ecological Research Network's study on Snowshoe hare physical data in the Bonanza Creek Experimental Forest. Using the data collected from 1999-2012, this report will analyze the counts and sizes of juvenile hares.

*COME BACK TO FINISH THIS  - add info on what the report contains*

## 2. Data and Methods
Snowshoe hare data and measurements were made accessible through Knut Kielland and associates at the Bonanza Creek LTER. The data contain measurements and observations on hares during a capture-recapture study done in Alaska's Tanana valley from 1999-2012. 

*COME BACK TO FINISH THIS - add info on stats tests and whats included* 

